#' Annotate cell types using DotPlot with different marker databases
#'
#' This function dynamically selects the appropriate annotation method based on the
#' `gene_list_type` parameter. It supports marker databases from Cellmarker2, PanglaoDB,
#' Seurat (via `FindAllMarkers`), or Excel files.
#'
#' @param seurat_obj A valid Seurat object with cluster annotations in `meta.data`.
#' @param gene_list A list of data frames containing marker genes and metrics.
#'     Format depends on `gene_list_type`:
#'     - **Cellmarker2**: Generated by `Markers_filter_Cellmarker2()`.
#'     - **PanglaoDB**: Generated by `Markers_filter_PanglaoDB()`.
#'     - **Seurat**: Generated by `read_seurat_markers()`.
#'     - **Excel**: Generated by `read_excel_markers()`.
#' @param gene_list_type Type of marker database to use. Must be one of:
#'     `"Cellmarker2"`, `"PanglaoDB"`, `"Seurat"`, or `"Excel"`.
#' @param species Species of the dataset: `"Human"` or `"Mouse"` for gene name standardization.
#' @param cluster_col Column name in `meta.data` defining clusters (default: `"seurat_clusters"`).
#' @param assay Assay layer in the Seurat object (default: `"RNA"`).
#' @param save_path Directory to save output PNGs. Must be explicitly specified.
#' @param min_counts Minimum number of counts for Cellmarker2 annotations (default: `1`).
#' @param metric_names Optional. Metric column names for custom labeling (used in "Seurat"/"Excel").
#' @param ... Additional parameters passed to the specific annotation function.
#'
#' @returns Saves cell type annotation PNGs in `save_path`. Returns invisibly.
#' @export
#' @family cell_annotation
#'
#' @importFrom stats setNames
#' @importFrom dplyr all_of
#' @importFrom Seurat Idents
#' @importFrom ggplot2 theme_minimal element_text element_blank
#' @importFrom patchwork wrap_plots
#' @importFrom cowplot plot_grid
#' @importFrom scales rescale
#'
#' @examples
#' \dontrun{
#' # Example for Cellmarker2
#' Celltype_annotation_Dotplot(
#'   seurat_obj = sce,
#'   gene_list = Markers_list_Cellmarker2,
#'   gene_list_type = "Cellmarker2",
#'   species = "Human",
#'   save_path = "./annotations/"
#' )
#'
#' # Example for Seurat marker list
#' Celltype_annotation_Dotplot(
#'   seurat_obj = sce,
#'   gene_list = Markers_list_Seurat,
#'   gene_list_type = "Seurat",
#'   species = "Human",
#'   save_path = "./annotations/",
#'   metric_names = c("pct.1", "avg_logFC", "p_val_adj")
#' )
#'
#' # Example for Excel marker list
#' Celltype_annotation_Dotplot(
#'   seurat_obj = sce,
#'   gene_list = Markers_list_Excel,
#'   gene_list_type = "Excel",
#'   species = "Mouse",
#'   save_path = "./annotations/"
#' )
#' }

Celltype_annotation_Dotplot <- function(
    seurat_obj,
    gene_list,
    gene_list_type,
    species,
    cluster_col = "seurat_clusters",
    assay = "RNA",
    save_path = NULL,
    min_counts = 1,
    metric_names = NULL,
    ...
) {
  if (!inherits(seurat_obj, "Seurat")) {
    stop("Input must be a Seurat object!", call. = FALSE)
  }
  if (!is.list(gene_list)) {
    stop("gene_list must be a list of data frames!", call. = FALSE)
  }
  if (!all(sapply(gene_list, is.data.frame))) {
    stop("Each element in gene_list must be a data frame!", call. = FALSE)
  }
  if (!gene_list_type %in% c("Cellmarker2", "PanglaoDB", "Seurat", "Excel")) {
    stop("gene_list_type must be one of 'Cellmarker2', 'PanglaoDB', 'Seurat', or 'Excel'", call. = FALSE)
  }
  if (species != "Human" && species != "Mouse") {
    stop("species must be 'Human' or 'Mouse'", call. = FALSE)
  }
  if (missing(save_path)) {
    stop("save_path must be explicitly specified", call. = FALSE)
  }
  if (!interactive() && !grepl(normalizePath(tempdir()), normalizePath(save_path), fixed = TRUE)) {
    warning("Writing to non-temporary locations is restricted. Using temporary directory instead.", immediate. = TRUE)
    save_path <- file.path(tempdir(), "Celltype_annotation_Dotplot_output")
  }

  dir.create(save_path, showWarnings = FALSE, recursive = TRUE)

  switch(gene_list_type,
         "Cellmarker2" = {
           if (!exists("Celltype_annotation_Cellmarker2", mode = "function")) {
             stop("Function 'Celltype_annotation_Cellmarker2' not found. Ensure it is defined or installed.", call. = FALSE)
           }
           Celltype_annotation_Cellmarker2(
             seurat_obj = seurat_obj,
             gene_list = gene_list,
             species = species,
             cluster_col = cluster_col,
             assay = assay,
             save_path = save_path,
             min_counts = min_counts,
             ...
           )
         },
         "PanglaoDB" = {
           if (!exists("Celltype_annotation_PanglaoDB", mode = "function")) {
             stop("Function 'Celltype_annotation_PanglaoDB' not found. Ensure it is defined or installed.", call. = FALSE)
           }
           Celltype_annotation_PanglaoDB(
             seurat_obj = seurat_obj,
             gene_list = gene_list,
             species = species,
             cluster_col = cluster_col,
             assay = assay,
             save_path = save_path,
             ...
           )
         },
         "Seurat" = {
           if (!exists("Celltype_annotation_Seurat", mode = "function")) {
             stop("Function 'Celltype_annotation_Seurat' not found. Ensure it is defined or installed.", call. = FALSE)
           }
           Celltype_annotation_Seurat(
             seurat_obj = seurat_obj,
             gene_list = gene_list,
             species = species,
             cluster_col = cluster_col,
             assay = assay,
             save_path = save_path,
             metric_names = metric_names,
             ...
           )
         },
         "Excel" = {
           if (!exists("Celltype_annotation_Excel", mode = "function")) {
             stop("Function 'Celltype_annotation_Excel' not found. Ensure it is defined or installed.", call. = FALSE)
           }
           Celltype_annotation_Excel(
             seurat_obj = seurat_obj,
             gene_list = gene_list,
             species = species,
             cluster_col = cluster_col,
             assay = assay,
             save_path = save_path,
             metric_names = metric_names,
             ...
           )
         }
  )

  message("Visualization saved to:", normalizePath(save_path))
  invisible()
}
