#' Plot Grouped Gene Z-Score Heatmap with Optional AUCell Integrated Row
#'
#' @description
#' Generates a publication-quality mean Z-score expression heatmap across cell 
#' groups from a Seurat object using \pkg{pheatmap}. Optionally computes and 
#' adds a top row representing the integrated pathway/marker expression score 
#' calculated via \pkg{AUCell}. Row annotations distinguish individual gene 
#' expression rows from the optional AUCell weighted row. Column annotations 
#' and row annotations are automatically styled using SlimR's internal discrete 
#' palettes.
#'
#' @section Colour palette:
#' Discrete annotation colors are generated by internal \code{paletteDiscrete()}
#' based on ArchR's palettes (*stallion* by default). Heatmap body values use a
#' classic blue-white-red (\code{RdBu} reversed) palette matching custom breaks.
#'
#' @param seurat_obj A Seurat object (supports both Seurat v4 and v5).
#' @param features A character vector of gene names to display in the heatmap.
#' @param group_by Character string specifying the column name in 
#'   \code{seurat_obj@meta.data} used to group cells (e.g., \code{"orig.ident"} 
#'   or \code{"celltype"}).
#' @param assay Character string specifying the assay to pull data from. 
#'   If \code{NULL}, uses \code{Seurat::DefaultAssay(seurat_obj)}.
#' @param slot_or_layer Character string specifying the layer/slot to extract. 
#'   Default is \code{"data"}.
#' @param add_aucell_row Logical. If \code{TRUE} (default), computes an integrated 
#'   expression score across \code{features} per cell using \pkg{AUCell} and 
#'   appends its group mean as the top row of the heatmap.
#' @param aucell_row_name Character string naming the top integrated AUCell row 
#'   when \code{add_aucell_row = TRUE}. Default is \code{"Integrated_Score"}.
#' @param cluster_rows Logical. Whether to perform hierarchical clustering on 
#'   rows. Default is \code{FALSE} to maintain input gene order.
#' @param cluster_cols Logical. Whether to perform hierarchical clustering on 
#'   columns. Default is \code{FALSE} to preserve original group ordering.
#' @param palette_set Character string naming the discrete palette set to use 
#'   for group/type annotation bars (e.g., \code{"stallion"}, \code{"bear"}, 
#'   \code{"calm"}). Default is \code{"stallion"}.
#' @param scale_range Numeric vector of length 2 defining the minimum and 
#'   maximum limits for the heatmap break range. Default is \code{c(-1.25, 1.25)}.
#' @param cellwidth Numeric. Width of individual heatmap cells in points. 
#'   Set to make cells square. Default is \code{18}.
#' @param cellheight Numeric. Height of individual heatmap cells in points. 
#'   Set to make cells square. Default is \code{18}.
#' @param main Character string for the main plot title. Default is 
#'   \code{"Group Gene Heatmap Plot | SlimR"}.
#'
#' @return A \pkg{pheatmap} object invisibly.
#'
#' @export
#'
#' @family Section_5_Other_Functions_Provided
#'
#' @importFrom Seurat DefaultAssay
#' @importFrom SeuratObject LayerData GetAssayData
#' @importFrom AUCell AUCell_buildRankings AUCell_calcAUC getAUC
#' @importFrom pheatmap pheatmap
#' @importFrom RColorBrewer brewer.pal
#' @importFrom grDevices colorRampPalette
#' @importFrom methods slot
#' @importFrom stats aggregate
#'
#' @examples
#' \dontrun{
#' # Basic expression heatmap without integrated AUCell row
#' Plot_Group_Gene_Heatmap(
#'   seurat_obj = sce,
#'   features = c("CD3D", "CD3E", "CD4", "CD8A"),
#'   group_by = "celltype",
#'   add_aucell_row = FALSE
#' )
#'
#' # With top AUCell pathway/marker integrated score row
#' Plot_Group_Gene_Heatmap(
#'   seurat_obj = sce,
#'   features = c("TNF", "IL6", "NFKB1", "RELA"),
#'   group_by = "orig.ident",
#'   add_aucell_row = TRUE,
#'   aucell_row_name = "NFkB_Pathway_AUC"
#' )
#' }
Plot_Group_Gene_Heatmap <- function(seurat_obj,
                                    features,
                                    group_by,
                                    assay = NULL,
                                    slot_or_layer = "data",
                                    add_aucell_row = TRUE,
                                    aucell_row_name = "Integrated_Score",
                                    cluster_rows = FALSE,
                                    cluster_cols = FALSE,
                                    palette_set = "stallion",
                                    scale_range = c(-1.25, 1.25),
                                    cellwidth = 18,
                                    cellheight = 18,
                                    main = "Group Gene Heatmap Plot | SlimR") {
  
  # ---------------------------------------------------------------------------
  # 1. Parameter Validation & Data Extraction
  # ---------------------------------------------------------------------------
  if (!group_by %in% colnames(seurat_obj@meta.data)) {
    stop(paste0("Column '", group_by, "' not found in seurat_obj@meta.data."))
  }
  
  if (is.null(assay)) {
    assay <- Seurat::DefaultAssay(seurat_obj)
  }
  
  # Safely extract expression matrix without triggering Seurat v5 internal %||% warning
  assay_obj <- seurat_obj[[assay]]
  exp_matrix <- tryCatch({
    # Seurat v5 layer access
    if (inherits(assay_obj, "Assay5")) {
      SeuratObject::LayerData(assay_obj, layer = slot_or_layer)
    } else {
      # Seurat v4 slot access
      SeuratObject::GetAssayData(assay_obj, slot = slot_or_layer)
    }
  }, error = function(e) {
    # Fallback method using standard S4 slot access
    methods::slot(assay_obj, slot_or_layer)
  })
  
  # Check missing features
  valid_features <- intersect(features, rownames(exp_matrix))
  if (length(valid_features) == 0) {
    stop("None of the specified 'features' were found in the expression matrix.")
  } else if (length(valid_features) < length(features)) {
    missing <- setdiff(features, valid_features)
    warning("The following features were not found and omitted: ", paste(missing, collapse = ", "))
  }
  
  # Group info vector
  cell_groups <- as.character(seurat_obj@meta.data[[group_by]])
  unique_groups <- unique(cell_groups)
  
  # ---------------------------------------------------------------------------
  # 2. Calculate Gene-Level Mean Expression per Group & Scale (Z-Score)
  # ---------------------------------------------------------------------------
  gene_mat <- as.matrix(exp_matrix[valid_features, , drop = FALSE])
  
  # Calculate mean expression per group for each gene
  group_mean_gene <- do.call(rbind, lapply(valid_features, function(g) {
    tapply(gene_mat[g, ], cell_groups, mean, na.rm = TRUE)
  }))
  rownames(group_mean_gene) <- valid_features
  group_mean_gene <- group_mean_gene[, unique_groups, drop = FALSE]
  
  # Perform Row Z-score normalization using standard base scale
  gene_zscore <- t(base::scale(t(group_mean_gene)))
  gene_zscore[is.na(gene_zscore)] <- 0 # Handle zero variance genes
  
  # ---------------------------------------------------------------------------
  # 3. Optional: AUCell Weighted/Integrated Row Calculation
  # ---------------------------------------------------------------------------
  if (add_aucell_row) {
    # Build AUCell Rankings
    gene_sets <- list(TargetSet = valid_features)
    cells_rankings <- AUCell::AUCell_buildRankings(exp_matrix, plotStats = FALSE, verbose = FALSE)
    cells_AUC <- AUCell::AUCell_calcAUC(gene_sets, cells_rankings, verbose = FALSE)
    auc_scores <- as.numeric(AUCell::getAUC(cells_AUC)["TargetSet", ])
    
    # Group mean for AUCell
    auc_group_mean <- tapply(auc_scores, cell_groups, mean, na.rm = TRUE)
    auc_group_mean <- auc_group_mean[unique_groups]
    
    # Scale AUCell score across groups (Z-score)
    auc_zscore <- base::scale(auc_group_mean)
    auc_zscore[is.na(auc_zscore)] <- 0 # Robustness handle for zero-variance AUC
    auc_zscore <- t(auc_zscore)
    rownames(auc_zscore) <- aucell_row_name
    
    # Combine AUCell row on top
    final_mat <- rbind(auc_zscore, gene_zscore)
  } else {
    final_mat <- gene_zscore
  }
  
  # ---------------------------------------------------------------------------
  # 4. Color Palette & Break Setup (Matching Image 2 Style)
  # ---------------------------------------------------------------------------
  colors <- rev(RColorBrewer::brewer.pal(n = 11, name = "RdBu"))
  colors_use <- grDevices::colorRampPalette(colors = colors)(100)
  
  min_val <- scale_range[1]
  max_val <- scale_range[2]
  
  my_breaks <- c(
    seq(min_val, 0, length.out = ceiling(100 / 2) + 1),
    seq(0.05, max_val, length.out = floor(100 / 2))
  )
  
  # Clamp extreme values to break bounds
  final_mat[final_mat < min_val] <- min_val
  final_mat[final_mat > max_val] <- max_val

  # ---------------------------------------------------------------------------
  # 5. Annotation Setup (Rows & Columns using paletteDiscrete)
  # ---------------------------------------------------------------------------
  # Column Annotation (Groups)
  annotation_col <- data.frame(
    Group = factor(colnames(final_mat), levels = unique_groups),
    row.names = colnames(final_mat)
  )
  
  # Row Annotation (Feature Type)
  row_types <- if (add_aucell_row) {
    c("Weighted expression", rep("Gene Expression", length(valid_features)))
  } else {
    rep("Gene Expression", length(valid_features))
  }
  
  annotation_row <- data.frame(
    Feature_Type = factor(row_types, levels = unique(row_types)),
    row.names = rownames(final_mat)
  )
  
  # Color Mapping Generation using internal paletteDiscrete
  col_group_colors <- paletteDiscrete(values = unique_groups, set = palette_set)
  col_row_type_colors <- c("Weighted expression" = "#4DAF4A", "Gene Expression" = "#377EB8")
  
  ann_colors <- list(
    Group = col_group_colors,
    Feature_Type = col_row_type_colors[unique(row_types)]
  )
  
  # ---------------------------------------------------------------------------
  # 6. Heatmap Plotting (Square cells with cellwidth/cellheight)
  # ---------------------------------------------------------------------------
  p <- pheatmap::pheatmap(
    mat = final_mat,
    color = colors_use,
    breaks = my_breaks,
    border_color = "white",
    cluster_rows = cluster_rows,
    cluster_cols = cluster_cols,
    annotation_col = annotation_col,
    annotation_row = annotation_row,
    annotation_colors = ann_colors,
    show_colnames = TRUE,
    show_rownames = TRUE,
    annotation_legend = TRUE,
    cellwidth = cellwidth,
    cellheight = cellheight,
    main = main
  )
  
  invisible(p)
}