#' Plot Grouped Gene Z-Score Heatmap with Optional Integrated Score Row
#'
#' @description
#' Generates a publication-quality mean Z-score expression heatmap across cell 
#' groups from a Seurat object using \pkg{pheatmap}. Optionally computes and 
#' appends a top row representing the integrated pathway or marker signature 
#' score (mean gene expression across target features per cell) before group 
#' mean calculation and Z-score scaling. Row annotations distinguish individual gene 
#' expression rows from the optional integrated weighted row. Column annotations 
#' and row annotations are automatically styled using SlimR's internal discrete 
#' palettes.
#'
#' @section Colour palette:
#' Discrete annotation colors are generated by internal \code{paletteDiscrete()}
#' based on ArchR's palettes (*stallion* by default). Heatmap body values use a
#' classic blue-white-red (\code{RdBu} reversed) palette matching custom breaks.
#'
#' @param seurat_obj A Seurat object (supports both Seurat v4 and v5).
#' @param features A character vector of gene names to display in the heatmap.
#' @param group_by Character string specifying the column name in 
#'   \code{seurat_obj@meta.data} used to group cells (e.g., \code{"orig.ident"} 
#'   or \code{"celltype"}).
#' @param assay Character string specifying the assay to pull data from. 
#'   If \code{NULL}, uses \code{Seurat::DefaultAssay(seurat_obj)}.
#' @param slot_or_layer Character string specifying the layer/slot to extract. 
#'   Default is \code{"data"}.
#' @param add_aucell_row Logical. If \code{TRUE} (default), computes an integrated 
#'   mean expression signature across \code{features} per cell and appends its 
#'   group-level mean Z-score as the top row of the heatmap.
#' @param aucell_row_name Character string naming the top integrated row 
#'   when \code{add_aucell_row = TRUE}. Default is \code{"Integrated_Score"}.
#' @param cluster_rows Logical. Whether to perform hierarchical clustering on 
#'   rows. Default is \code{FALSE} to maintain input gene order.
#' @param cluster_cols Logical. Whether to perform hierarchical clustering on 
#'   columns. Default is \code{FALSE} to preserve original group ordering.
#' @param palette_set Character string naming the discrete palette set to use 
#'   for group/type annotation bars (e.g., \code{"stallion"}, \code{"bear"}, 
#'   \code{"calm"}). Default is \code{"stallion"}.
#' @param scale_range Numeric vector of length 2 defining the minimum and 
#'   maximum limits for the heatmap break range. Default is \code{c(-1.25, 1.25)}.
#' @param annotation_legend Logical. Whether to show legends for the column and row 
#'   annotations (e.g., Group and Feature Type color bars). Default is \code{FALSE}.
#' @param cellwidth Numeric. Width of individual heatmap cells in points. 
#'   Set to make cells square. Default is \code{18}.
#' @param cellheight Numeric. Height of individual heatmap cells in points. 
#'   Set to make cells square. Default is \code{18}.
#' @param main Character string for the main plot title. Default is 
#'   \code{"Group Gene Heatmap Plot | SlimR"}.
#'
#' @return A \pkg{pheatmap} object invisibly.
#'
#' @export
#'
#' @family Section_5_Other_Functions_Provided
#'
#' @importFrom Seurat DefaultAssay FetchData
#' @importFrom pheatmap pheatmap
#' @importFrom RColorBrewer brewer.pal
#' @importFrom grDevices colorRampPalette
#' @importFrom methods slot
#'
#' @examples
#' \dontrun{
#' # Basic expression heatmap without integrated row
#' Plot_Group_Gene_Heatmap(
#'   seurat_obj = sce,
#'   features = c("CD3D", "CD3E", "CD4", "CD8A"),
#'   group_by = "celltype",
#'   add_aucell_row = FALSE
#' )
#'
#' # With top integrated gene signature score row
#' Plot_Group_Gene_Heatmap(
#'   seurat_obj = sce,
#'   features = c("TNF", "IL6", "NFKB1", "RELA"),
#'   group_by = "orig.ident",
#'   add_aucell_row = TRUE,
#'   aucell_row_name = "NFkB_Pathway_AUC"
#' )
#' }
Plot_Group_Gene_Heatmap <- function(seurat_obj,
                                    features,
                                    group_by,
                                    assay = NULL,
                                    slot_or_layer = "data",
                                    add_aucell_row = TRUE,
                                    aucell_row_name = "Integrated_Score",
                                    cluster_rows = FALSE,
                                    cluster_cols = FALSE,
                                    palette_set = "stallion",
                                    scale_range = c(-1.25, 1.25),
                                    annotation_legend = FALSE,
                                    cellwidth = 18,
                                    cellheight = 18,
                                    main = "Group Gene Heatmap Plot | SlimR") {
  
  # ---------------------------------------------------------------------------
  # 1. Parameter Validation & Factor Levels Lock
  # ---------------------------------------------------------------------------
  if (!group_by %in% colnames(seurat_obj@meta.data)) {
    stop(paste0("Column '", group_by, "' not found in seurat_obj@meta.data."))
  }
  
  if (is.null(assay)) {
    assay <- Seurat::DefaultAssay(seurat_obj)
  }
  
  # Strictly preserve existing Factor levels or maintain natural appearance order
  group_vec <- seurat_obj@meta.data[[group_by]]
  if (is.factor(group_vec)) {
    unique_groups <- levels(droplevels(group_vec))
  } else {
    unique_groups <- unique(group_vec)
  }
  cell_groups <- as.character(group_vec)
  
  # ---------------------------------------------------------------------------
  # 2. Fast Target-Only Data Extraction via FetchData (Memory & Speed Optimized)
  # ---------------------------------------------------------------------------
  # Check missing features
  all_genes_in_obj <- rownames(seurat_obj[[assay]])
  valid_features <- features[features %in% all_genes_in_obj] # Keep user's exact input order
  
  if (length(valid_features) == 0) {
    stop("None of the specified 'features' were found in the specified assay.")
  } else if (length(valid_features) < length(features)) {
    missing <- setdiff(features, valid_features)
    warning("The following features were not found and omitted: ", paste(missing, collapse = ", "))
  }
  
  # Fetch ONLY the requested gene features (cells x features)
  fetched_data <- Seurat::FetchData(
    object = seurat_obj,
    vars = valid_features,
    layer = slot_or_layer,
    assay = assay
  )
  
  # Transpose to (features x cells) matrix
  gene_mat <- t(as.matrix(fetched_data))
  
  # ---------------------------------------------------------------------------
  # 3. Calculate Gene-Level Mean Expression per Group & Scale (Z-Score)
  # ---------------------------------------------------------------------------
  # Calculate mean expression per group for each gene
  group_mean_gene <- do.call(rbind, lapply(valid_features, function(g) {
    tapply(gene_mat[g, ], cell_groups, mean, na.rm = TRUE)
  }))
  rownames(group_mean_gene) <- valid_features
  
  # Force matrix column order to STRICTLY match unique_groups
  group_mean_gene <- group_mean_gene[, intersect(unique_groups, colnames(group_mean_gene)), drop = FALSE]
  
  # Perform Row Z-score normalization using standard base scale
  gene_zscore <- t(base::scale(t(group_mean_gene)))
  gene_zscore[is.na(gene_zscore)] <- 0 # Handle zero variance genes
  
  # ---------------------------------------------------------------------------
  # 4. Optional: Integrated Signature Weighted Row Calculation (Mean Expression)
  # ---------------------------------------------------------------------------
  if (add_aucell_row) {
    # Calculate cell-level mean expression across target features
    cell_integrated_score <- colMeans(gene_mat, na.rm = TRUE)
    
    # Calculate group-level mean of the integrated score
    integrated_group_mean <- tapply(cell_integrated_score, cell_groups, mean, na.rm = TRUE)
    integrated_group_mean <- integrated_group_mean[colnames(gene_zscore)] # Lock group order
    
    # Scale integrated score across groups (Z-score)
    integrated_zscore <- base::scale(integrated_group_mean)
    integrated_zscore[is.na(integrated_zscore)] <- 0 # Handle zero-variance
    integrated_zscore <- t(integrated_zscore)
    rownames(integrated_zscore) <- aucell_row_name
    
    # Combine Integrated row on top
    final_mat <- rbind(integrated_zscore, gene_zscore)
  } else {
    final_mat <- gene_zscore
  }
  
  # ---------------------------------------------------------------------------
  # 5. Color Palette & Break Setup
  # ---------------------------------------------------------------------------
  colors <- rev(RColorBrewer::brewer.pal(n = 11, name = "RdBu"))
  colors_use <- grDevices::colorRampPalette(colors = colors)(100)
  
  min_val <- scale_range[1]
  max_val <- scale_range[2]
  
  my_breaks <- c(
    seq(min_val, 0, length.out = ceiling(100 / 2) + 1),
    seq(0.05, max_val, length.out = floor(100 / 2))
  )
  
  # Clamp extreme values to break bounds
  final_mat[final_mat < min_val] <- min_val
  final_mat[final_mat > max_val] <- max_val

  # ---------------------------------------------------------------------------
  # 6. Annotation Setup (Dynamic Feature_Type Column Header & Exact Ordering)
  # ---------------------------------------------------------------------------
  current_cols <- colnames(final_mat)
  
  # Column Annotation (Groups) - Factor levels MUST match current_cols
  annotation_col <- data.frame(
    Group = factor(current_cols, levels = current_cols),
    row.names = current_cols
  )
  
  # Row Annotation (Feature Type Header & Labels)
  feature_type_header <- if (add_aucell_row) {
    "Weighted / Genes"
  } else {
    "Gene"
  }
  
  row_types <- if (add_aucell_row) {
    c("Weighted expression", rep("Gene Expression", length(valid_features)))
  } else {
    rep("Gene Expression", length(valid_features))
  }
  
  annotation_row <- data.frame(
    Type = factor(row_types, levels = unique(row_types)),
    row.names = rownames(final_mat)
  )
  colnames(annotation_row) <- feature_type_header
  
  # Color Mapping Generation using internal paletteDiscrete
  col_group_colors <- paletteDiscrete(values = current_cols, set = palette_set)
  col_row_type_colors <- c("Weighted expression" = "#4DAF4A", "Gene Expression" = "#377EB8")
  
  ann_colors <- list(
    Group = col_group_colors
  )
  ann_colors[[feature_type_header]] <- col_row_type_colors[unique(row_types)]
  
  # ---------------------------------------------------------------------------
  # 7. Heatmap Plotting
  # ---------------------------------------------------------------------------
  p <- pheatmap::pheatmap(
    mat = final_mat,
    color = colors_use,
    breaks = my_breaks,
    border_color = "black",
    cluster_rows = cluster_rows,
    cluster_cols = cluster_cols,
    annotation_col = annotation_col,
    annotation_row = annotation_row,
    annotation_colors = ann_colors,
    show_colnames = TRUE,
    show_rownames = TRUE,
    annotation_legend = annotation_legend,
    cellwidth = cellwidth,
    cellheight = cellheight,
    main = main
  )
  
  invisible(p)
}
