#' Create "Marker_list" from Seurat object
#'
#' @param df Dataframe generated by "FindAllMarkers" function, recommend
#'     to use parameter "group.by = "Cell_type"" and "only.pos = TRUE".
#' @param sources Type of markers sources to use. Be one of: `"Seurat"` or `"presto"`.
#' @param sort_by Marker sorting parameter, select "avg_log2FC" or "p_val_adj".
#'     Default parameters use "sort_by = 'avg_log2FC'".
#' @param gene_filter The number of markers left for each cell type based
#'     on the "sort_by" parameter's level of difference. Default parameters use
#'     "gene_fliter = 20"
#'
#' @returns The standardized "Marker_list" in the SlimR package.
#' @export
#' @family Standardized_Marker_list_Input
#'
#' @importFrom utils head
#'
#' @examples
#'\dontrun{
#' # Example for Seurat sources markers
#' seurat_markers <- Seurat::FindAllMarkers(
#'     seurat_obj = sce,
#'     group.by = "Cell_type",
#'     only.pos = TRUE)
#'
#' Markers_list_Seurat <- read_seurat_markers(seurat_markers,
#'     sources = "Seurat",
#'     sort_by = "avg_log2FC",
#'     gene_filter = 10
#'     )
#'
#' # Example for presto sources markers
#' seurat_markers <- presto::wilcoxauc(
#'     seurat_obj = sce,
#'     group_by = "Cell_type",
#'     seurat_assay = "RNA"
#'     ) %>%
#'     filter(padj < 0.05, logFC > 0.5)
#'
#' Markers_list_Seurat <- read_seurat_markers(seurat_markers,
#'     sources = "presto",
#'     sort_by = "logFC",
#'     gene_filter = 10
#'     )
#' }
#'
#'
read_seurat_markers <- function(df,
                         sources = c("Seurat", "presto"),
                         sort_by = NULL,
                         gene_filter = 20) {
  sources <- match.arg(sources)

  if (!is.numeric(gene_filter)) {
    stop("'gene_filter' must be a numeric value")
  }
  if (gene_filter < 1) {
    stop("'gene_filter' must be a positive integer")
  }

  if (is.null(sort_by)) {
    sort_by <- if (sources == "Seurat") "avg_log2FC" else "logFC"
  }

  config <- list(
    Seurat = list(
      cluster_col = "cluster",
      sort_opts = c("avg_log2FC", "p_val_adj"),
      output_cols = c("gene", "avg_log2FC", "p_val_adj", "p_val", "pct.1", "pct.2")
    ),
    presto = list(
      cluster_col = "group",
      sort_opts = c("logFC", "padj"),
      output_cols = c("feature", "logFC", "padj", "pval", "pct_in", "pct_out")
    )
  )

  conf <- config[[sources]]

  if (!sort_by %in% conf$sort_opts) {
    stop("'sort_by' must be one of: ",
         paste(conf$sort_opts, collapse = ", "))
  }

  required_cols <- c(conf$cluster_col, sort_by, conf$output_cols)
  missing_cols <- setdiff(required_cols, colnames(df))
  if (length(missing_cols) > 0) {
    stop("Missing required columns: ",
         paste(missing_cols, collapse = ", "))
  }

  clusters <- split(df, df[[conf$cluster_col]])

  processed <- lapply(clusters, function(cluster_df) {
    if (sort_by == conf$sort_opts[1]) {
      sorted_df <- cluster_df[order(-cluster_df[[sort_by]]), , drop = FALSE]
    } else {
      sorted_df <- cluster_df[order(cluster_df[[sort_by]]), , drop = FALSE]
    }

    filtered_df <- head(sorted_df, gene_filter)

    reordered_df <- filtered_df[, conf$output_cols, drop = FALSE]

    return(reordered_df)
  })

  names(processed) <- names(clusters)
  return(processed)
}
